### ISSUE TITLE
[website] application does not work on Firefox

### ISSUE THREAD

**Issue by pgte** [PixelsCamp/docs#3]
Looks like an CORS issue on the API endpoint:

![banners_and_alerts_e_apply_-_pixels_camp](https://cloud.githubusercontent.com/assets/47910/17966973/87754c16-6abc-11e6-891e-39bf509dcb25.png)

**Comment by bmartins** [comment]
Hi, we're aware of the issue and working on a fix. logout and login again, you should be fine

**Comment by celso** [comment]
Closing.
